"""task_requests table

Revision ID: 1af3c861b592
Revises: 60faafa4fcbd
Create Date: 2026-04-25 17:45:11.440342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af3c861b592'
down_revision: Union[str, None] = '60faafa4fcbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('CHANGE', 'REMOVE', 'ADD', 'QUESTION', name='requesttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'RESOLVED', name='requeststatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('proposed_book_id', sa.Integer(), nullable=True),
    sa.Column('proposed_section_id', sa.Integer(), nullable=True),
    sa.Column('proposed_count', sa.Integer(), nullable=True),
    sa.Column('proposed_date', sa.Date(), nullable=True),
    sa.Column('teacher_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposed_book_id'], ['books.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_section_id'], ['book_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_requests_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_requests_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_requests_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_requests_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_task_requests_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_requests_student_id'))
        batch_op.drop_index(batch_op.f('ix_task_requests_status'))

    op.drop_table('task_requests')
    # ### end Alembic commands ###
