"""suggestion_feedback table

Revision ID: 60faafa4fcbd
Revises: a75e236e10f4
Create Date: 2026-04-24 17:35:15.148992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60faafa4fcbd'
down_revision: Union[str, None] = 'a75e236e10f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_section_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('REJECTED', 'ACCEPTED', name='feedbackaction'), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_section_id'], ['book_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'book_id', 'book_section_id', 'day_of_week', 'action', name='uq_feedback_key')
    )
    with op.batch_alter_table('suggestion_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestion_feedback_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_feedback_book_section_id'), ['book_section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_feedback_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestion_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_feedback_student_id'))
        batch_op.drop_index(batch_op.f('ix_suggestion_feedback_book_section_id'))
        batch_op.drop_index(batch_op.f('ix_suggestion_feedback_book_id'))

    op.drop_table('suggestion_feedback')
    # ### end Alembic commands ###
