"""initial schema

Revision ID: a75e236e10f4
Revises: 
Create Date: 2026-04-23 22:59:50.031428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75e236e10f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'name', name='uq_academic_year_teacher_name')
    )
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_years_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('TEACHER', 'STUDENT', name='userrole'), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('grade_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'name', name='uq_subject_teacher_name')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('TEST', 'VIDEO', 'OZET', 'TEKRAR', 'OTHER', name='tasktype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_student_id'), ['student_id'], unique=False)

    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('SORU_BANKASI', 'FASIKUL', 'KONU_ANLATIMLI', 'BRANS_DENEMESI', 'GENEL_DENEME', name='booktype'), nullable=False),
    sa.Column('avg_questions_per_test', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('book_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('test_count', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_sections_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_sections_topic_id'), ['topic_id'], unique=False)

    op.create_table('student_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'book_id', name='uq_student_book')
    )
    with op.batch_alter_table('student_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_books_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_books_student_id'), ['student_id'], unique=False)

    op.create_table('section_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_book_id', sa.Integer(), nullable=False),
    sa.Column('book_section_id', sa.Integer(), nullable=False),
    sa.Column('reserved_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_section_id'], ['book_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_book_id'], ['student_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_book_id', 'book_section_id', name='uq_section_progress')
    )
    with op.batch_alter_table('section_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_progress_book_section_id'), ['book_section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_section_progress_student_book_id'), ['student_book_id'], unique=False)

    op.create_table('task_book_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_section_id', sa.Integer(), nullable=False),
    sa.Column('planned_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('wrong_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['book_section_id'], ['book_sections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_book_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_book_items_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_book_items_book_section_id'), ['book_section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_book_items_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_book_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_book_items_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_book_items_book_section_id'))
        batch_op.drop_index(batch_op.f('ix_task_book_items_book_id'))

    op.drop_table('task_book_items')
    with op.batch_alter_table('section_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_progress_student_book_id'))
        batch_op.drop_index(batch_op.f('ix_section_progress_book_section_id'))

    op.drop_table('section_progress')
    with op.batch_alter_table('student_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_books_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_books_book_id'))

    op.drop_table('student_books')
    with op.batch_alter_table('book_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_sections_topic_id'))
        batch_op.drop_index(batch_op.f('ix_book_sections_book_id'))

    op.drop_table('book_sections')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_topics_subject_id'))
        batch_op.drop_index(batch_op.f('ix_topics_parent_id'))

    op.drop_table('topics')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_books_subject_id'))

    op.drop_table('books')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_student_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_date'))

    op.drop_table('tasks')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_teacher_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_academic_year_id'))

    op.drop_table('users')
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_years_teacher_id'))

    op.drop_table('academic_years')
    # ### end Alembic commands ###
