/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * V2 Login
         * @description E-posta + şifre → Set-Cookie ile JWT'ler kuruldu. Body'de sade user özeti.
         *
         *     api_v1/auth.py:api_login ile aynı lockout + audit + generic error mesajı
         *     politikası — kullanıcı sızıntısı (e-posta enumeration) önlenir.
         */
        post: operations["v2_login_api_v2_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * V2 Refresh
         * @description Refresh cookie → yeni access cookie.
         *
         *     Refresh token rotation YOK (stateless, v1 ile aynı). Refresh süresi
         *     dolana kadar aynı refresh ile yeni access alınır. Şifre değişirse
         *     pwd_stamp mismatch ile refresh de revoke olur.
         *
         *     Cevap body'sinde güncel user — frontend "still logged in" doğrulayabilir.
         */
        post: operations["v2_refresh_api_v2_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * V2 Logout
         * @description Cookie'leri sil + audit yaz.
         *
         *     Auth ZORUNLU DEĞİL — geçersiz cookie ile de istek 200 döner (kullanıcı
         *     deneyimi: "logout" her zaman çalışır, hata göstermez). Audit yalnız
         *     cookie'den user çözebilirse yazılır.
         */
        post: operations["v2_logout_api_v2_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * V2 Auth Me
         * @description Kolaylık endpoint'i — Next.js middleware kullanıcı çözmek için çağırır.
         *
         *     `/api/v2/me` ile aynı user'ı döner ama Dalga 1'in MyAccountResponse şişmiş
         *     payload'ını taşımaz; sadece UserPublic. İstek başına maliyet minimum.
         */
        get: operations["v2_auth_me_api_v2_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Profil + kurum + veli bağları + KVKK durumu + son 20 talep.
         *
         *     Eşdeğer Jinja: app/routes/me.py:44-81 (me_page). Aynı veri, JSON şeklinde.
         */
        get: operations["get_me_api_v2_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/data-export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export My Data
         * @description KVKK madde 11 — kişisel veri ihracı.
         *
         *     Eşdeğer Jinja: app/routes/me.py:84-107. Anlık üretilir; DataSubjectRequest
         *     kayıt edilir (denetim izi). JSON dosyası attachment olarak iner.
         */
        get: operations["export_my_data_api_v2_me_data_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/data-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Data Delete
         * @description 30 günlük grace period'lu silme talebi (RTBF).
         *
         *     Eşdeğer Jinja: app/routes/me.py:110-129. İdempotent (kvkk.py:348-361):
         *     bekleyen talep varsa onu döner.
         */
        post: operations["request_data_delete_api_v2_me_data_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/data-delete/{request_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel My Delete Request
         * @description Bekleyen silme talebini iptal et.
         *
         *     Eşdeğer Jinja: app/routes/me.py:132-151. Yetki kontrolü
         *     `app/services/kvkk.py:385-420` içinde (kendi talebi + admin yetkileri).
         */
        post: operations["cancel_my_delete_request_api_v2_me_data_delete__request_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessTokenOut */
        AccessTokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
            /** Access Expires In */
            access_expires_in: number;
        };
        /** Body_accept_suggestion_teacher_students__student_id__suggestions_accept_post */
        Body_accept_suggestion_teacher_students__student_id__suggestions_accept_post: {
            /** Task Date */
            task_date: string;
            /** Book Id */
            book_id: number;
            /** Section Id */
            section_id: number;
            /** Planned Count */
            planned_count: number;
        };
        /** Body_account_history_archive_admin_account_history_archive_post */
        Body_account_history_archive_admin_account_history_archive_post: {
            /** Record Type */
            record_type: string;
            /** Record Id */
            record_id: number;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Return To
             * @default
             */
            return_to: string;
        };
        /** Body_account_history_bulk_archive_admin_account_history_bulk_archive_post */
        Body_account_history_bulk_archive_admin_account_history_bulk_archive_post: {
            /** Owner Type */
            owner_type: string;
            /** Owner Id */
            owner_id: number;
            /**
             * Years
             * @default 3
             */
            years: number;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Return To
             * @default
             */
            return_to: string;
        };
        /** Body_account_history_unarchive_admin_account_history_unarchive_post */
        Body_account_history_unarchive_admin_account_history_unarchive_post: {
            /** Record Type */
            record_type: string;
            /** Record Id */
            record_id: number;
            /**
             * Return To
             * @default
             */
            return_to: string;
        };
        /** Body_add_item_teacher_tasks__task_id__items_post */
        Body_add_item_teacher_tasks__task_id__items_post: {
            /** Book Id */
            book_id: number;
            /** Section Id */
            section_id: number;
            /** Planned Count */
            planned_count: number;
        };
        /** Body_add_section_teacher_books__book_id__sections_post */
        Body_add_section_teacher_books__book_id__sections_post: {
            /** Label */
            label: string;
            /**
             * Topic Id
             * @default
             */
            topic_id: string;
            /** Test Count */
            test_count: number;
        };
        /** Body_admin_kvkk_reject_admin_kvkk_requests__request_id__reject_post */
        Body_admin_kvkk_reject_admin_kvkk_requests__request_id__reject_post: {
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_ai_suggest_sections_teacher_books__book_id__ai_suggest_post */
        Body_ai_suggest_sections_teacher_books__book_id__ai_suggest_post: {
            /**
             * Grade Hint
             * @default
             */
            grade_hint: string;
        };
        /** Body_announcements_create_admin_announcements_post */
        Body_announcements_create_admin_announcements_post: {
            /**
             * Title
             * @default
             */
            title: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @default info
             */
            severity: string;
            /**
             * Audience
             * @default all
             */
            audience: string;
            /**
             * Starts At
             * @default
             */
            starts_at: string;
            /**
             * Ends At
             * @default
             */
            ends_at: string;
            /**
             * Dismissible
             * @default on
             */
            dismissible: string;
        };
        /** Body_apply_template_to_book_teacher_books__book_id__apply_template_post */
        Body_apply_template_to_book_teacher_books__book_id__apply_template_post: {
            /** Template Id */
            template_id: number;
            /**
             * Overwrite
             * @default
             */
            overwrite: string;
        };
        /** Body_approve_teacher_requests__req_id__approve_post */
        Body_approve_teacher_requests__req_id__approve_post: {
            /**
             * Response
             * @default
             */
            response: string;
        };
        /** Body_ask_question_student_tasks__task_id__question_post */
        Body_ask_question_student_tasks__task_id__question_post: {
            /** Message */
            message: string;
        };
        /** Body_change_user_role_admin_users__user_id__change_role_post */
        Body_change_user_role_admin_users__user_id__change_role_post: {
            /** New Role */
            new_role: string;
            /**
             * Institution Id
             * @default
             */
            institution_id: string;
        };
        /** Body_create_book_teacher_books_post */
        Body_create_book_teacher_books_post: {
            /** Name */
            name: string;
            /**
             * Publisher
             * @default
             */
            publisher: string;
            /** Subject Id */
            subject_id: number;
            /** Type */
            type: string;
            /**
             * Avg Questions Per Test
             * @default
             */
            avg_questions_per_test: string;
            /**
             * Target Grade Min
             * @default
             */
            target_grade_min: string;
            /**
             * Target Grade Max
             * @default
             */
            target_grade_max: string;
            /**
             * Target Graduate
             * @default
             */
            target_graduate: string;
            /**
             * Template Id
             * @default
             */
            template_id: string;
        };
        /** Body_create_institution_admin_institutions_post */
        Body_create_institution_admin_institutions_post: {
            /** Name */
            name: string;
            /**
             * Slug
             * @default
             */
            slug: string;
            /**
             * Contact Email
             * @default
             */
            contact_email: string;
            /**
             * Plan
             * @default free
             */
            plan: string;
        };
        /** Body_create_invitation_institution_invitations_post */
        Body_create_invitation_institution_invitations_post: {
            /**
             * Full Name
             * @default
             */
            full_name: string;
            /**
             * Email
             * @default
             */
            email: string;
        };
        /** Body_create_phase_teacher_years__year_id__phases_post */
        Body_create_phase_teacher_years__year_id__phases_post: {
            /** Name */
            name: string;
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string;
            /**
             * Kind
             * @default REGULAR
             */
            kind: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** Body_create_set_teacher_book_sets_post */
        Body_create_set_teacher_book_sets_post: {
            /** Name */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** Body_create_student_teacher_students_post */
        Body_create_student_teacher_students_post: {
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /**
             * Grade
             * @default 8
             */
            grade: string;
            /**
             * Academic Year Id
             * @default
             */
            academic_year_id: string;
            /**
             * Track
             * @default
             */
            track: string;
            /**
             * Graduate Mode
             * @default
             */
            graduate_mode: string;
            /**
             * Entry Year Grade9
             * @default
             */
            entry_year_grade9: string;
        };
        /** Body_create_task_teacher_students__student_id__tasks_post */
        Body_create_task_teacher_students__student_id__tasks_post: {
            /** Task Date */
            task_date: string;
            /**
             * Type
             * @default test
             */
            type: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Book Id
             * @default
             */
            book_id: string;
            /**
             * Section Id
             * @default
             */
            section_id: string;
            /**
             * Planned Count
             * @default
             */
            planned_count: string;
            /**
             * Scheduled Hour
             * @default
             */
            scheduled_hour: string;
            /**
             * Link Url
             * @default
             */
            link_url: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Subject Label
             * @default
             */
            subject_label: string;
            /**
             * Keep Open
             * @default
             */
            keep_open: string;
        };
        /** Body_create_teacher_institution_teachers_post */
        Body_create_teacher_institution_teachers_post: {
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
        };
        /** Body_create_user_admin_users_post */
        Body_create_user_admin_users_post: {
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /**
             * Institution Id
             * @default
             */
            institution_id: string;
        };
        /** Body_create_year_teacher_years_post */
        Body_create_year_teacher_years_post: {
            /** Start Year */
            start_year: string;
        };
        /** Body_crm_action_add_admin_revenue_institutions__institution_id__crm_actions_add_post */
        Body_crm_action_add_admin_revenue_institutions__institution_id__crm_actions_add_post: {
            /** Kind */
            kind: string;
            /** Summary */
            summary: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Result
             * @default pending
             */
            result: string;
            /**
             * Follow Up At
             * @default
             */
            follow_up_at: string;
        };
        /** Body_crm_action_complete_admin_revenue_institutions__institution_id__crm_actions__action_id__complete_post */
        Body_crm_action_complete_admin_revenue_institutions__institution_id__crm_actions__action_id__complete_post: {
            /** Result */
            result: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** Body_crm_note_add_admin_revenue_institutions__institution_id__crm_notes_add_post */
        Body_crm_note_add_admin_revenue_institutions__institution_id__crm_notes_add_post: {
            /** Content */
            content: string;
            /**
             * Pinned
             * @default
             */
            pinned: string;
        };
        /** Body_edit_institution_admin_institutions__institution_id__edit_post */
        Body_edit_institution_admin_institutions__institution_id__edit_post: {
            /** Name */
            name: string;
            /**
             * Contact Email
             * @default
             */
            contact_email: string;
            /**
             * Plan
             * @default free
             */
            plan: string;
            /**
             * Is Active
             * @default
             */
            is_active: string;
        };
        /** Body_edit_section_teacher_books__book_id__sections__section_id__edit_post */
        Body_edit_section_teacher_books__book_id__sections__section_id__edit_post: {
            /** Label */
            label: string;
            /** Test Count */
            test_count: number;
        };
        /** Body_edit_set_teacher_book_sets__set_id__edit_post */
        Body_edit_set_teacher_book_sets__set_id__edit_post: {
            /** Name */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** Body_edit_task_teacher_tasks__task_id__edit_post */
        Body_edit_task_teacher_tasks__task_id__edit_post: {
            /**
             * Type
             * @default test
             */
            type: string;
            /**
             * Title
             * @default
             */
            title: string;
            /** Task Date */
            task_date: string;
            /**
             * Book Id
             * @default
             */
            book_id: string;
            /**
             * Section Id
             * @default
             */
            section_id: string;
            /**
             * Planned Count
             * @default
             */
            planned_count: string;
            /**
             * Scheduled Hour
             * @default
             */
            scheduled_hour: string;
            /**
             * Link Url
             * @default
             */
            link_url: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** Body_edit_user_admin_users__user_id__edit_post */
        Body_edit_user_admin_users__user_id__edit_post: {
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /**
             * Institution Id
             * @default
             */
            institution_id: string;
            /**
             * Is Active
             * @default
             */
            is_active: string;
        };
        /** Body_feature_catalog_create_admin_feature_catalog_new_post */
        Body_feature_catalog_create_admin_feature_catalog_new_post: {
            /**
             * Slug
             * @default
             */
            slug: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Tagline
             * @default
             */
            tagline: string;
            /**
             * Description Md
             * @default
             */
            description_md: string;
            /**
             * Icon
             * @default sparkles
             */
            icon: string;
            /**
             * Accent Color
             * @default #3b82f6
             */
            accent_color: string;
            /**
             * Category Icon
             * @default ✨
             */
            category_icon: string;
            /**
             * Category Label
             * @default
             */
            category_label: string;
            /**
             * Demo Duration Label
             * @default
             */
            demo_duration_label: string;
            /**
             * Mockup Type
             * @default
             */
            mockup_type: string;
            /**
             * Target Roles
             * @default []
             */
            target_roles: string[];
            /**
             * Benefits Text
             * @default
             */
            benefits_text: string;
            /**
             * Pain Points Text
             * @default
             */
            pain_points_text: string;
            /**
             * Demo Slug
             * @default
             */
            demo_slug: string;
            /**
             * Domain
             * @default genel
             */
            domain: string;
            /**
             * Tier
             * @default enhancement
             */
            tier: string;
            /**
             * Status Field
             * @default draft
             */
            status_field: string;
            /**
             * Introduced At
             * @default
             */
            introduced_at: string;
            /**
             * Introduced In Commit
             * @default
             */
            introduced_in_commit: string;
            /**
             * Pr Url
             * @default
             */
            pr_url: string;
            /**
             * Strategic Priority
             * @default 3
             */
            strategic_priority: number;
            /**
             * Manual Pin
             * @default
             */
            manual_pin: string;
            /**
             * Pin Until
             * @default
             */
            pin_until: string;
            /**
             * Manual Hide
             * @default
             */
            manual_hide: string;
            /**
             * Cta Label
             * @default Detayları gör
             */
            cta_label: string;
            /**
             * Cta Url
             * @default
             */
            cta_url: string;
        };
        /** Body_feature_catalog_pin_admin_feature_catalog__card_id__pin_post */
        Body_feature_catalog_pin_admin_feature_catalog__card_id__pin_post: {
            /**
             * Pinned
             * @default
             */
            pinned: string;
            /**
             * Pin Until
             * @default
             */
            pin_until: string;
        };
        /** Body_feature_catalog_status_admin_feature_catalog__card_id__status_post */
        Body_feature_catalog_status_admin_feature_catalog__card_id__status_post: {
            /** Status Field */
            status_field: string;
        };
        /** Body_feature_catalog_update_admin_feature_catalog__card_id__post */
        Body_feature_catalog_update_admin_feature_catalog__card_id__post: {
            /**
             * Slug
             * @default
             */
            slug: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Tagline
             * @default
             */
            tagline: string;
            /**
             * Description Md
             * @default
             */
            description_md: string;
            /**
             * Icon
             * @default sparkles
             */
            icon: string;
            /**
             * Accent Color
             * @default #3b82f6
             */
            accent_color: string;
            /**
             * Category Icon
             * @default ✨
             */
            category_icon: string;
            /**
             * Category Label
             * @default
             */
            category_label: string;
            /**
             * Demo Duration Label
             * @default
             */
            demo_duration_label: string;
            /**
             * Mockup Type
             * @default
             */
            mockup_type: string;
            /**
             * Target Roles
             * @default []
             */
            target_roles: string[];
            /**
             * Benefits Text
             * @default
             */
            benefits_text: string;
            /**
             * Pain Points Text
             * @default
             */
            pain_points_text: string;
            /**
             * Demo Slug
             * @default
             */
            demo_slug: string;
            /**
             * Domain
             * @default genel
             */
            domain: string;
            /**
             * Tier
             * @default enhancement
             */
            tier: string;
            /**
             * Status Field
             * @default draft
             */
            status_field: string;
            /**
             * Introduced At
             * @default
             */
            introduced_at: string;
            /**
             * Introduced In Commit
             * @default
             */
            introduced_in_commit: string;
            /**
             * Pr Url
             * @default
             */
            pr_url: string;
            /**
             * Strategic Priority
             * @default 3
             */
            strategic_priority: number;
            /**
             * Manual Pin
             * @default
             */
            manual_pin: string;
            /**
             * Pin Until
             * @default
             */
            pin_until: string;
            /**
             * Manual Hide
             * @default
             */
            manual_hide: string;
            /**
             * Cta Label
             * @default Detayları gör
             */
            cta_label: string;
            /**
             * Cta Url
             * @default
             */
            cta_url: string;
        };
        /** Body_feature_flag_add_override_admin_feature_flags__flag_id__overrides_post */
        Body_feature_flag_add_override_admin_feature_flags__flag_id__overrides_post: {
            /** Institution Id */
            institution_id: number;
            /**
             * Enabled
             * @default on
             */
            enabled: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_impersonate_user_admin_users__user_id__impersonate_post */
        Body_impersonate_user_admin_users__user_id__impersonate_post: {
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** Body_import_confirm_teacher_students_import_confirm_post */
        Body_import_confirm_teacher_students_import_confirm_post: {
            /**
             * Csv Text
             * @default
             */
            csv_text: string;
        };
        /** Body_import_preview_teacher_students_import_preview_post */
        Body_import_preview_teacher_students_import_preview_post: {
            /**
             * Csv Text
             * @default
             */
            csv_text: string;
        };
        /** Body_import_results_csv_teacher_students_import_results_csv_post */
        Body_import_results_csv_teacher_students_import_results_csv_post: {
            /**
             * Payload
             * @default
             */
            payload: string;
        };
        /** Body_institution_contact_save_admin_revenue_institutions__institution_id__contact_save_post */
        Body_institution_contact_save_admin_revenue_institutions__institution_id__contact_save_post: {
            /**
             * Responsible Person Name
             * @default
             */
            responsible_person_name: string;
            /**
             * Responsible Person Title
             * @default
             */
            responsible_person_title: string;
            /**
             * Billing Email
             * @default
             */
            billing_email: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Whatsapp
             * @default
             */
            whatsapp: string;
            /**
             * Linkedin Url
             * @default
             */
            linkedin_url: string;
            /**
             * Website
             * @default
             */
            website: string;
            /**
             * Address
             * @default
             */
            address: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_institution_tag_add_admin_revenue_institutions__institution_id__tags_add_post */
        Body_institution_tag_add_admin_revenue_institutions__institution_id__tags_add_post: {
            /** Kind */
            kind: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_invitation_accept_parent_invitation__token__accept_post */
        Body_invitation_accept_parent_invitation__token__accept_post: {
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
            /** Password Confirm */
            password_confirm: string;
            /**
             * Kvkk Accept
             * @default
             */
            kvkk_accept: string;
        };
        /** Body_invite_parent_teacher_students__student_id__parents_invite_post */
        Body_invite_parent_teacher_students__student_id__parents_invite_post: {
            /** Invited Email */
            invited_email: string;
            /**
             * Relation
             * @default diger
             */
            relation: string;
            /**
             * Is Primary
             * @default
             */
            is_primary: string;
        };
        /** Body_invoice_cancel_admin_invoices__invoice_id__cancel_post */
        Body_invoice_cancel_admin_invoices__invoice_id__cancel_post: {
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_invoice_mark_paid_admin_invoices__invoice_id__mark_paid_post */
        Body_invoice_mark_paid_admin_invoices__invoice_id__mark_paid_post: {
            /**
             * Method
             * @default manual
             */
            method: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_invoice_postpone_admin_invoices__invoice_id__postpone_post */
        Body_invoice_postpone_admin_invoices__invoice_id__postpone_post: {
            /**
             * Days
             * @default 7
             */
            days: number;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_invoice_send_reminder_admin_invoices__invoice_id__send_reminder_post */
        Body_invoice_send_reminder_admin_invoices__invoice_id__send_reminder_post: {
            /**
             * Kind
             * @default manual
             */
            kind: string;
        };
        /** Body_login_submit_login_post */
        Body_login_submit_login_post: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Cf Turnstile Response
             * @default
             */
            cf_turnstile_response: string;
        };
        /** Body_me_data_delete_request_me_data_delete_post */
        Body_me_data_delete_request_me_data_delete_post: {
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Confirm
             * @default
             */
            confirm: string;
        };
        /** Body_notify_parents_program_teacher_students__student_id__program_notify_parents_post */
        Body_notify_parents_program_teacher_students__student_id__program_notify_parents_post: {
            /** Start */
            start: string;
        };
        /** Body_offer_create_admin_revenue_institutions__institution_id__offers_create_post */
        Body_offer_create_admin_revenue_institutions__institution_id__offers_create_post: {
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /**
             * Value
             * @default
             */
            value: string;
            /**
             * Duration Months
             * @default
             */
            duration_months: string;
            /**
             * New Plan
             * @default
             */
            new_plan: string;
            /**
             * Public Message
             * @default
             */
            public_message: string;
            /**
             * Admin Note
             * @default
             */
            admin_note: string;
            /**
             * Expires In Days
             * @default 14
             */
            expires_in_days: number;
            /**
             * Send Now
             * @default
             */
            send_now: string;
        };
        /** Body_offer_public_decline_offers__token__decline_post */
        Body_offer_public_decline_offers__token__decline_post: {
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** Body_password_change_submit_password_change_post */
        Body_password_change_submit_password_change_post: {
            /**
             * Current Password
             * @default
             */
            current_password: string;
            /** New Password */
            new_password: string;
            /** Confirm Password */
            confirm_password: string;
        };
        /** Body_promote_student_teacher_students__student_id__promote_post */
        Body_promote_student_teacher_students__student_id__promote_post: {
            /** Grade */
            grade: string;
            /**
             * Academic Year Id
             * @default
             */
            academic_year_id: string;
            /**
             * Track
             * @default
             */
            track: string;
            /**
             * Graduate Mode
             * @default
             */
            graduate_mode: string;
            /**
             * Entry Year Grade9
             * @default
             */
            entry_year_grade9: string;
        };
        /** Body_publish_day_tasks_teacher_students__student_id__publish_day_post */
        Body_publish_day_tasks_teacher_students__student_id__publish_day_post: {
            /** Task Date */
            task_date: string;
        };
        /** Body_publish_week_tasks_teacher_students__student_id__publish_week_post */
        Body_publish_week_tasks_teacher_students__student_id__publish_week_post: {
            /** Week Start */
            week_start: string;
        };
        /** Body_reject_suggestion_teacher_students__student_id__suggestions_reject_post */
        Body_reject_suggestion_teacher_students__student_id__suggestions_reject_post: {
            /** Task Date */
            task_date: string;
            /** Book Id */
            book_id: number;
            /** Section Id */
            section_id: number;
        };
        /** Body_reject_teacher_requests__req_id__reject_post */
        Body_reject_teacher_requests__req_id__reject_post: {
            /**
             * Response
             * @default
             */
            response: string;
        };
        /** Body_reorder_tasks_teacher_students__student_id__tasks_reorder_post */
        Body_reorder_tasks_teacher_students__student_id__tasks_reorder_post: {
            /** Task Date */
            task_date: string;
            /** Task Ids */
            task_ids: string;
        };
        /** Body_request_add_student_day__day_iso__request_add_post */
        Body_request_add_student_day__day_iso__request_add_post: {
            /** Book Id */
            book_id: number;
            /** Section Id */
            section_id: number;
            /** Proposed Count */
            proposed_count: number;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** Body_request_change_student_tasks__task_id__request_change_post */
        Body_request_change_student_tasks__task_id__request_change_post: {
            /** Proposed Count */
            proposed_count: number;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** Body_request_remove_student_tasks__task_id__request_remove_post */
        Body_request_remove_student_tasks__task_id__request_remove_post: {
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** Body_request_replace_student_tasks__task_id__request_replace_post */
        Body_request_replace_student_tasks__task_id__request_replace_post: {
            /** New Book Id */
            new_book_id: number;
            /** New Section Id */
            new_section_id: number;
            /** New Count */
            new_count: number;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** Body_respond_teacher_requests__req_id__respond_post */
        Body_respond_teacher_requests__req_id__respond_post: {
            /** Response */
            response: string;
        };
        /** Body_revenue_action_template_create_admin_revenue_action_templates_create_post */
        Body_revenue_action_template_create_admin_revenue_action_templates_create_post: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Body */
            body: string;
            /**
             * Subject
             * @default
             */
            subject: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** Body_revenue_action_template_update_admin_revenue_action_templates__template_id__update_post */
        Body_revenue_action_template_update_admin_revenue_action_templates__template_id__update_post: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Kind
             * @default
             */
            kind: string;
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Subject
             * @default
             */
            subject: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Is Active
             * @default
             */
            is_active: string;
        };
        /** Body_revenue_campaigns_create_admin_revenue_campaigns_create_post */
        Body_revenue_campaigns_create_admin_revenue_campaigns_create_post: {
            /** Name */
            name: string;
            /** Segment */
            segment: string;
            /** Variant A Kind */
            variant_a_kind: string;
            /** Variant A Title */
            variant_a_title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Admin Note
             * @default
             */
            admin_note: string;
            /**
             * Filter Plan
             * @default
             */
            filter_plan: string;
            /**
             * Variant A Value
             * @default
             */
            variant_a_value: string;
            /**
             * Variant A Duration Months
             * @default
             */
            variant_a_duration_months: string;
            /**
             * Variant A New Plan
             * @default
             */
            variant_a_new_plan: string;
            /**
             * Variant A Public Message
             * @default
             */
            variant_a_public_message: string;
            /**
             * Has Variant B
             * @default
             */
            has_variant_b: string;
            /**
             * Variant B Kind
             * @default
             */
            variant_b_kind: string;
            /**
             * Variant B Title
             * @default
             */
            variant_b_title: string;
            /**
             * Variant B Value
             * @default
             */
            variant_b_value: string;
            /**
             * Variant B Duration Months
             * @default
             */
            variant_b_duration_months: string;
            /**
             * Variant B New Plan
             * @default
             */
            variant_b_new_plan: string;
            /**
             * Variant B Public Message
             * @default
             */
            variant_b_public_message: string;
            /**
             * Offer Expires In Days
             * @default 14
             */
            offer_expires_in_days: number;
        };
        /** Body_revenue_campaigns_preview_admin_revenue_campaigns_preview_post */
        Body_revenue_campaigns_preview_admin_revenue_campaigns_preview_post: {
            /** Segment */
            segment: string;
            /**
             * Filter Plan
             * @default
             */
            filter_plan: string;
        };
        /** Body_revenue_quick_action_admin_revenue_action_center_quick_action_post */
        Body_revenue_quick_action_admin_revenue_action_center_quick_action_post: {
            /** Institution Id */
            institution_id: number;
            /** Kind */
            kind: string;
            /** Summary */
            summary: string;
            /**
             * Result
             * @default pending
             */
            result: string;
            /**
             * Follow Up Days
             * @default 0
             */
            follow_up_days: number;
        };
        /** Body_save_book_as_template_teacher_books__book_id__save_as_template_post */
        Body_save_book_as_template_teacher_books__book_id__save_as_template_post: {
            /**
             * Template Name
             * @default
             */
            template_name: string;
        };
        /** Body_security_monitor_abuse_resolve_admin_security_monitor_abuse__signal_id__resolve_post */
        Body_security_monitor_abuse_resolve_admin_security_monitor_abuse__signal_id__resolve_post: {
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_security_monitor_alarms_update_rule_admin_security_monitor_alarms_rules__rule_id__update_post */
        Body_security_monitor_alarms_update_rule_admin_security_monitor_alarms_rules__rule_id__update_post: {
            /** Threshold */
            threshold: number;
            /** Cooldown Minutes */
            cooldown_minutes: number;
            /**
             * Enabled
             * @default 0
             */
            enabled: number;
            /**
             * Channels
             * @default email,in_app
             */
            channels: string;
        };
        /** Body_security_monitor_block_ip_admin_security_monitor_ips_block_post */
        Body_security_monitor_block_ip_admin_security_monitor_ips_block_post: {
            /** Ip */
            ip: string;
            /**
             * Hours
             * @default 1
             */
            hours: number;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_security_monitor_system_resolve_admin_security_monitor_system__error_id__resolve_post */
        Body_security_monitor_system_resolve_admin_security_monitor_system__error_id__resolve_post: {
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_security_monitor_unblock_ip_admin_security_monitor_ips_unblock_post */
        Body_security_monitor_unblock_ip_admin_security_monitor_ips_unblock_post: {
            /** Ip */
            ip: string;
        };
        /** Body_send_parent_note_teacher_students__student_id__parent_note_post */
        Body_send_parent_note_teacher_students__student_id__parent_note_post: {
            /** Body */
            body: string;
        };
        /** Body_set_item_completed_student_tasks__task_id__items__item_id__set_completed_post */
        Body_set_item_completed_student_tasks__task_id__items__item_id__set_completed_post: {
            /** Completed */
            completed: number;
        };
        /** Body_set_week_anchor_teacher_students__student_id__set_week_anchor_post */
        Body_set_week_anchor_teacher_students__student_id__set_week_anchor_post: {
            /** Anchor */
            anchor: string;
            /**
             * Return To
             * @default week
             */
            return_to: string;
        };
        /** Body_signup_invite_submit_signup_invite__token__post */
        Body_signup_invite_submit_signup_invite__token__post: {
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Password Confirm */
            password_confirm: string;
            /**
             * Accept Terms
             * @default
             */
            accept_terms: string;
        };
        /** Body_signup_teacher_submit_signup_teacher_post */
        Body_signup_teacher_submit_signup_teacher_post: {
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Password Confirm */
            password_confirm: string;
            /**
             * Accept Terms
             * @default
             */
            accept_terms: string;
        };
        /** Body_student_focus_end_and_break_student_focus__session_id__end_and_break_post */
        Body_student_focus_end_and_break_student_focus__session_id__end_and_break_post: {
            /**
             * Actual Minutes
             * @default 0
             */
            actual_minutes: number;
            /**
             * Interrupted
             * @default
             */
            interrupted: string;
            /**
             * Break Kind
             * @default short_break
             */
            break_kind: string;
            /**
             * Break Minutes
             * @default 5
             */
            break_minutes: number;
        };
        /** Body_student_focus_end_student_focus__session_id__end_post */
        Body_student_focus_end_student_focus__session_id__end_post: {
            /**
             * Actual Minutes
             * @default 0
             */
            actual_minutes: number;
            /**
             * Interrupted
             * @default
             */
            interrupted: string;
        };
        /** Body_student_focus_start_student_focus_start_post */
        Body_student_focus_start_student_focus_start_post: {
            /**
             * Planned Minutes
             * @default 25
             */
            planned_minutes: number;
            /**
             * Kind
             * @default work
             */
            kind: string;
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** Body_student_review_rate_student_review__card_id__post */
        Body_student_review_rate_student_review__card_id__post: {
            /** Rating */
            rating: number;
        };
        /** Body_student_update_progress_student_goals__goal_id__update_progress_post */
        Body_student_update_progress_student_goals__goal_id__update_progress_post: {
            /**
             * Current Value
             * @default
             */
            current_value: string;
        };
        /** Body_super_admin_add_bonus_admin_usage__owner_type___owner_id__bonus_post */
        Body_super_admin_add_bonus_admin_usage__owner_type___owner_id__bonus_post: {
            /** Bonus Amount */
            bonus_amount: number;
        };
        /** Body_super_admin_quota_set_override_admin_quota__institution_id__override_post */
        Body_super_admin_quota_set_override_admin_quota__institution_id__override_post: {
            /** Quota Key */
            quota_key: string;
            /** Override Value */
            override_value: number;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_teacher_create_goal_teacher_students__student_id__goals_create_post */
        Body_teacher_create_goal_teacher_students__student_id__goals_create_post: {
            /** Title */
            title: string;
            /**
             * Kind
             * @default custom
             */
            kind: string;
            /**
             * Parent Id
             * @default
             */
            parent_id: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Target Value
             * @default
             */
            target_value: string;
            /**
             * Current Value
             * @default
             */
            current_value: string;
            /**
             * Unit
             * @default
             */
            unit: string;
            /**
             * Target Date
             * @default
             */
            target_date: string;
        };
        /** Body_teacher_mute_at_risk_teacher_at_risk__student_id__mute_post */
        Body_teacher_mute_at_risk_teacher_at_risk__student_id__mute_post: {
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** Body_teacher_seed_subject_teacher_students__student_id__review_seed_post */
        Body_teacher_seed_subject_teacher_students__student_id__review_seed_post: {
            /** Subject Id */
            subject_id: number;
        };
        /** Body_teacher_student_dna_notify_parent_teacher_students__student_id__dna_notify_parent_post */
        Body_teacher_student_dna_notify_parent_teacher_students__student_id__dna_notify_parent_post: {
            /** Body */
            body: string;
        };
        /** Body_teacher_update_goal_teacher_goals__goal_id__update_post */
        Body_teacher_update_goal_teacher_goals__goal_id__update_post: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Target Value
             * @default
             */
            target_value: string;
            /**
             * Current Value
             * @default
             */
            current_value: string;
            /**
             * Unit
             * @default
             */
            unit: string;
            /**
             * Target Date
             * @default
             */
            target_date: string;
        };
        /** Body_test_email_teacher_settings_test_email_post */
        Body_test_email_teacher_settings_test_email_post: {
            /** To */
            to: string;
        };
        /** Body_toggle_child_mute_parent_settings_students__student_id__mute_post */
        Body_toggle_child_mute_parent_settings_students__student_id__mute_post: {
            /**
             * Muted
             * @default
             */
            muted: string;
        };
        /** Body_update_cron_schedule_teacher_settings_cron__schedule_id__post */
        Body_update_cron_schedule_teacher_settings_cron__schedule_id__post: {
            /** Hour */
            hour: number;
            /**
             * Minute
             * @default 0
             */
            minute: number;
            /**
             * Day Of Week
             * @default
             */
            day_of_week: string;
            /**
             * Enabled
             * @default
             */
            enabled: string;
        };
        /** Body_update_preferences_parent_settings_preferences_post */
        Body_update_preferences_parent_settings_preferences_post: {
            /**
             * Daily Summary
             * @default
             */
            daily_summary: string;
            /**
             * Weekly Report
             * @default
             */
            weekly_report: string;
            /**
             * Empty Day
             * @default
             */
            empty_day: string;
            /**
             * New Program
             * @default
             */
            new_program: string;
            /**
             * Drop Alert
             * @default
             */
            drop_alert: string;
            /**
             * Teacher Note
             * @default
             */
            teacher_note: string;
            /**
             * Exam Approaching
             * @default
             */
            exam_approaching: string;
            /**
             * Quiet Start
             * @default 22:00
             */
            quiet_start: string;
            /**
             * Quiet End
             * @default 07:00
             */
            quiet_end: string;
        };
        /** Body_user_contact_save_admin_revenue_users__user_id__contact_save_post */
        Body_user_contact_save_admin_revenue_users__user_id__contact_save_post: {
            /**
             * Responsible Person Name
             * @default
             */
            responsible_person_name: string;
            /**
             * Responsible Person Title
             * @default
             */
            responsible_person_title: string;
            /**
             * Billing Email
             * @default
             */
            billing_email: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Whatsapp
             * @default
             */
            whatsapp: string;
            /**
             * Linkedin Url
             * @default
             */
            linkedin_url: string;
            /**
             * Website
             * @default
             */
            website: string;
            /**
             * Address
             * @default
             */
            address: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_user_crm_action_add_admin_revenue_users__user_id__crm_actions_add_post */
        Body_user_crm_action_add_admin_revenue_users__user_id__crm_actions_add_post: {
            /** Kind */
            kind: string;
            /** Summary */
            summary: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Result
             * @default pending
             */
            result: string;
            /**
             * Follow Up At
             * @default
             */
            follow_up_at: string;
        };
        /** Body_user_crm_action_complete_admin_revenue_users__user_id__crm_actions__action_id__complete_post */
        Body_user_crm_action_complete_admin_revenue_users__user_id__crm_actions__action_id__complete_post: {
            /** Result */
            result: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** Body_user_crm_note_add_admin_revenue_users__user_id__crm_notes_add_post */
        Body_user_crm_note_add_admin_revenue_users__user_id__crm_notes_add_post: {
            /** Content */
            content: string;
            /**
             * Pinned
             * @default
             */
            pinned: string;
        };
        /** Body_user_offer_create_admin_revenue_users__user_id__offers_create_post */
        Body_user_offer_create_admin_revenue_users__user_id__offers_create_post: {
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /**
             * Value
             * @default
             */
            value: string;
            /**
             * Duration Months
             * @default
             */
            duration_months: string;
            /**
             * New Plan
             * @default
             */
            new_plan: string;
            /**
             * Public Message
             * @default
             */
            public_message: string;
            /**
             * Admin Note
             * @default
             */
            admin_note: string;
            /**
             * Expires In Days
             * @default 14
             */
            expires_in_days: number;
            /**
             * Send Now
             * @default
             */
            send_now: string;
        };
        /** Body_user_tag_add_admin_revenue_users__user_id__tags_add_post */
        Body_user_tag_add_admin_revenue_users__user_id__tags_add_post: {
            /** Kind */
            kind: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Body_week_notes_add_teacher_students__student_id__week_notes_add_post */
        Body_week_notes_add_teacher_students__student_id__week_notes_add_post: {
            /** Week Start */
            week_start: string;
            /** Body */
            body: string;
        };
        /** Body_whatsapp_start_parent_settings_whatsapp_start_post */
        Body_whatsapp_start_parent_settings_whatsapp_start_post: {
            /** Phone */
            phone: string;
        };
        /** Body_whatsapp_verify_parent_settings_whatsapp_verify_post */
        Body_whatsapp_verify_parent_settings_whatsapp_verify_post: {
            /** Code */
            code: string;
        };
        /**
         * DataDeleteRequestBody
         * @description POST /api/v2/me/data-delete body.
         */
        DataDeleteRequestBody: {
            /** Reason */
            reason?: string | null;
            /** Confirm */
            confirm: boolean;
        };
        /**
         * DataDeleteResponse
         * @description POST /api/v2/me/data-delete data alanı.
         */
        DataDeleteResponse: {
            /** Request Id */
            request_id: number;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /**
             * Can Cancel Until
             * Format: date-time
             */
            can_cancel_until: string;
        };
        /**
         * DataRequestSummary
         * @description KVKK talep özeti — son 20 talep listesinde + detayda.
         */
        DataRequestSummary: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "export" | "delete" | "rectify";
            /** Kind Label Tr */
            kind_label_tr: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "completed" | "cancelled" | "rejected";
            /** Status Label Tr */
            status_label_tr: string;
            /** Reason */
            reason?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Process After */
            process_after?: string | null;
            /** Processed At */
            processed_at?: string | null;
            /** Can Cancel */
            can_cancel: boolean;
        };
        /** DaySummaryOut */
        DaySummaryOut: {
            /** Date */
            date: string;
            /** Total Tasks */
            total_tasks: number;
            /** Total Items */
            total_items: number;
            /** Planned Count */
            planned_count: number;
            /** Completed Count */
            completed_count: number;
        };
        /** FocusEndIn */
        FocusEndIn: {
            /** Actual Minutes */
            actual_minutes?: number | null;
            /**
             * Interrupted
             * @default false
             */
            interrupted: boolean;
        };
        /** FocusStartIn */
        FocusStartIn: {
            /**
             * Planned Minutes
             * @default 25
             */
            planned_minutes: number;
            /**
             * Kind
             * @default work
             */
            kind: string;
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** FocusTodayOut */
        FocusTodayOut: {
            active_session: components["schemas"]["PomodoroSessionOut"] | null;
            /** Work Minutes Today */
            work_minutes_today: number;
            /** Sessions Today */
            sessions_today: number;
            /** Streak Days */
            streak_days: number;
            /** Points */
            points: number;
            /** Recent Sessions */
            recent_sessions: components["schemas"]["PomodoroSessionOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InstitutionRef
         * @description Kurum özet referansı — /me yanıtında istisnasız.
         */
        InstitutionRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
        };
        /**
         * KvkkStatus
         * @description Hesap KVKK durum özeti — pending delete varsa hangi tarih.
         */
        KvkkStatus: {
            /** Has Pending Delete */
            has_pending_delete: boolean;
            /** Pending Delete Request Id */
            pending_delete_request_id?: number | null;
            /** Pending Delete Scheduled At */
            pending_delete_scheduled_at?: string | null;
            /**
             * Can Export
             * @default true
             */
            can_export: boolean;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MutationResponse[DataDeleteResponse] */
        MutationResponse_DataDeleteResponse_: {
            data: components["schemas"]["DataDeleteResponse"];
            /**
             * Invalidate
             * @default []
             */
            invalidate: string[];
        };
        /** MutationResponse[SimpleOk] */
        MutationResponse_SimpleOk_: {
            data: components["schemas"]["SimpleOk"];
            /**
             * Invalidate
             * @default []
             */
            invalidate: string[];
        };
        /**
         * MyAccountResponse
         * @description GET /api/v2/me — sayfanın tek istekte ihtiyacı olan her şey.
         */
        MyAccountResponse: {
            user: components["schemas"]["UserPublic"];
            institution?: components["schemas"]["InstitutionRef"] | null;
            /**
             * Parent Links
             * @default []
             */
            parent_links: components["schemas"]["ParentLinkRef"][];
            kvkk_status: components["schemas"]["KvkkStatus"];
            /**
             * Recent Requests
             * @default []
             */
            recent_requests: components["schemas"]["DataRequestSummary"][];
        };
        /**
         * ParentLinkRef
         * @description Veli ↔ öğrenci eşleşmesi (yön role'a göre).
         *
         *     Veli ise counterpart = öğrenci; öğrenci ise counterpart = veli.
         */
        ParentLinkRef: {
            /** Link Id */
            link_id: number;
            /** Counterpart Id */
            counterpart_id: number;
            /** Counterpart Name */
            counterpart_name: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "anne" | "baba" | "vasi" | "diger";
            /** Relation Label Tr */
            relation_label_tr: string;
            /** Is Primary */
            is_primary: boolean;
        };
        /** PomodoroSessionOut */
        PomodoroSessionOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Label */
            label: string | null;
            /** Planned Minutes */
            planned_minutes: number;
            /** Actual Minutes */
            actual_minutes: number | null;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Interrupted */
            interrupted: boolean;
        };
        /** RatingIn */
        RatingIn: {
            /** Rating */
            rating: number;
        };
        /** ReviewBreakdownOut */
        ReviewBreakdownOut: {
            /** New */
            new: number;
            /** Learning */
            learning: number;
            /** Review */
            review: number;
            /** Relearning */
            relearning: number;
            /** Due Now */
            due_now: number;
            /** Total */
            total: number;
        };
        /** ReviewCardOut */
        ReviewCardOut: {
            /** Id */
            id: number;
            /** Topic Id */
            topic_id: number;
            /** Topic Name */
            topic_name: string | null;
            /** Subject Name */
            subject_name: string | null;
            /** State */
            state: number;
            /** State Label */
            state_label: string;
            /** Due At */
            due_at: string | null;
            /** Stability */
            stability: number;
            /** Difficulty */
            difficulty: number;
            /** Reps */
            reps: number;
            /** Lapses */
            lapses: number;
        };
        /** ReviewIndexOut */
        ReviewIndexOut: {
            /** Due Cards */
            due_cards: components["schemas"]["ReviewCardOut"][];
            breakdown: components["schemas"]["ReviewBreakdownOut"];
            /** Rating Labels */
            rating_labels: {
                [key: string]: string;
            };
        };
        /** ReviewResultOut */
        ReviewResultOut: {
            /** Card Id */
            card_id: number;
            /** New State */
            new_state: number;
            /** New State Label */
            new_state_label: string;
            /** Next Due At */
            next_due_at: string | null;
            /** Stability */
            stability: number;
        };
        /**
         * SimpleOk
         * @description Yan etkisi olmayan onay response'u.
         */
        SimpleOk: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Message */
            message?: string | null;
        };
        /** StudentDetailOut */
        StudentDetailOut: {
            student: components["schemas"]["StudentSummaryOut"];
            /** Today Planned */
            today_planned: number;
            /** Today Completed */
            today_completed: number;
            /** Week Planned */
            week_planned: number;
            /** Week Completed */
            week_completed: number;
            /** Rate 7D */
            rate_7d: number;
            /** Rate 30D */
            rate_30d: number;
            /** Consistency 7D */
            consistency_7d: number;
            /** Hit Rate 7D */
            hit_rate_7d: number;
            /** Worst Warning Level */
            worst_warning_level: string;
            /** Warnings */
            warnings: Record<string, never>[];
        };
        /** StudentListOut */
        StudentListOut: {
            /** Students */
            students: components["schemas"]["StudentSummaryOut"][];
            /** Total */
            total: number;
        };
        /** StudentSummaryOut */
        StudentSummaryOut: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Grade Level */
            grade_level: number | null;
            /** Is Graduate */
            is_graduate: boolean;
            /** Is Active */
            is_active: boolean;
            /** Grade Label */
            grade_label: string;
            /** Exam Label */
            exam_label: string;
        };
        /** TaskItemOut */
        TaskItemOut: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number | null;
            /** Book Title */
            book_title: string | null;
            /** Section Id */
            section_id: number | null;
            /** Section Title */
            section_title: string | null;
            /** Topic Name */
            topic_name: string | null;
            /** Planned Count */
            planned_count: number;
            /** Completed Count */
            completed_count: number;
        };
        /** TaskOut */
        TaskOut: {
            /** Id */
            id: number;
            /** Date */
            date: string;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Order */
            order: number;
            /** Items */
            items: components["schemas"]["TaskItemOut"][];
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * TelemetryEventIn
         * @description Anasayfa kartı olay bildirimi (sendBeacon body'si).
         */
        TelemetryEventIn: {
            /** Slug */
            slug: string;
            /** Event */
            event: string;
            /** Variant */
            variant?: string | null;
        };
        /** TodayOut */
        TodayOut: {
            summary: components["schemas"]["DaySummaryOut"];
            /** Tasks */
            tasks: components["schemas"]["TaskOut"][];
        };
        /** TokenPairOut */
        TokenPairOut: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
            /** Access Expires In */
            access_expires_in: number;
            /** Refresh Expires In */
            refresh_expires_in: number;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Role */
            role: string;
            /** Grade Level */
            grade_level?: number | null;
            /**
             * Is Graduate
             * @default false
             */
            is_graduate: boolean;
            /** Institution Id */
            institution_id?: number | null;
            /** Institution Name */
            institution_name?: string | null;
            /**
             * Must Change Password
             * @default false
             */
            must_change_password: boolean;
        };
        /**
         * UserPublic
         * @description Kullanıcı kamuya açık alanları — password REDACTED.
         */
        UserPublic: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "super_admin" | "institution_admin" | "teacher" | "student" | "parent";
            /** Institution Id */
            institution_id?: number | null;
            /** Is Active */
            is_active: boolean;
            /** Must Change Password */
            must_change_password: boolean;
            /** Last Login At */
            last_login_at?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** LoginOut */
        app__routes__api_v1__auth__LoginOut: {
            tokens: components["schemas"]["TokenPairOut"];
            user: components["schemas"]["UserOut"];
        };
        /**
         * LoginOut
         * @description Login response — token gövdede yok, cookie'de.
         *
         *     `must_change_password=True` ise frontend kullanıcıyı /password/change'e
         *     yönlendirmeli; `get_current_user_v2` aksi halde 403 atar (R-001 azaltması).
         */
        app__routes__api_v2__auth__LoginOut: {
            user: components["schemas"]["UserPublic"];
            /** Must Change Password */
            must_change_password: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v2_login_api_v2_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__routes__api_v2__auth__LoginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    v2_refresh_api_v2_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    v2_logout_api_v2_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    v2_auth_me_api_v2_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    get_me_api_v2_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyAccountResponse"];
                };
            };
        };
    };
    export_my_data_api_v2_me_data_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    request_data_delete_api_v2_me_data_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataDeleteRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse_DataDeleteResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_my_delete_request_api_v2_me_data_delete__request_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse_SimpleOk_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
