from app.models.abuse_signal import (
    ABUSE_KIND_DESCRIPTIONS_TR,
    ABUSE_KIND_LABELS_TR,
    AbuseSignal,
    DEDUP_WINDOW_HOURS as ABUSE_DEDUP_WINDOW_HOURS,
    SEVERITY_BADGE_COLOR as ABUSE_SEVERITY_BADGE_COLOR,
    SEVERITY_LABELS_TR as ABUSE_SEVERITY_LABELS_TR,
    THRESHOLD_MASS_INVITATION_PER_HOUR,
    THRESHOLD_MASS_NOTIFICATION_PER_HOUR,
    THRESHOLD_MULTI_ACCOUNT_DISTINCT_USERS,
    THRESHOLD_UNSUBSCRIBE_SPIKE_PER_DAY,
)
from app.models.active_session import (
    TERMINATION_REASON_LABELS_TR,
    ActiveSession,
)
from app.models.alarm import (
    DEFAULT_RULES as ALARM_DEFAULT_RULES,
    AlarmEvent,
    AlarmRule,
)
from app.models.error_event import (
    ERROR_RETENTION_DAYS,
    ErrorEvent,
    SLOW_REQUEST_THRESHOLD_MS,
    SLOW_RETENTION_DAYS,
    SlowRequestLog,
)
from app.models.impersonation_session import (
    IMPERSONATION_END_REASON_LABELS_TR,
    IMPERSONATION_MAX_DURATION_MINUTES,
    ImpersonationSession,
    REASON_MAX_LENGTH as IMPERSONATION_REASON_MAX_LENGTH,
    REASON_MIN_LENGTH as IMPERSONATION_REASON_MIN_LENGTH,
)
from app.models.suspicious_ip import (
    BLOCK_REASON_LABELS_TR,
    SuspiciousIp,
)
from app.models.academic import (
    ACADEMIC_PHASE_CAPACITY_MULTIPLIER,
    ACADEMIC_PHASE_KIND_BADGES,
    ACADEMIC_PHASE_KIND_LABELS,
    ACADEMIC_PHASE_NO_SCHOOL,
    EXAM_TARGET_LABELS,
    AcademicPhase,
    AcademicPhaseKind,
    AcademicYear,
    ExamTarget,
)
from app.models.addon import (
    ADDON_DESCRIPTIONS_TR,
    ADDON_LABELS_TR,
    ADDON_MONTHLY_PRICE_TRY,
    ADDON_MONTHLY_QUOTA,
    Addon,
    AddonKind,
)
from app.models.admin_digest import AdminWeeklyDigest
from app.models.announcement import (
    AUDIENCE_LABELS_TR,
    SEVERITY_LABELS_TR,
    AnnouncementAudience,
    AnnouncementSeverity,
    SystemAnnouncement,
)
from app.models.at_risk_mute import (
    AT_RISK_MUTE_DAYS,
    AtRiskMute,
    default_mute_expiry as at_risk_mute_default_expiry,
)
from app.models.audit_log import AUDIT_ACTION_LABELS, AuditAction, AuditLog
from app.models.book import (
    Book,
    BookSection,
    BookSet,
    BookSetItem,
    BookTemplate,
    BookTemplateSection,
    BookType,
)
from app.models.cron import CronSchedule
from app.models.data_subject_request import (
    DATA_REQUEST_KIND_LABELS_TR,
    DATA_REQUEST_STATUS_LABELS_TR,
    DELETE_GRACE_PERIOD_DAYS,
    DataRequestKind,
    DataRequestStatus,
    DataSubjectRequest,
)
from app.models.feature_card import (
    FEATURE_DOMAIN_LABELS_TR,
    FEATURE_STATUS_BADGES,
    FEATURE_STATUS_LABELS_TR,
    FEATURE_TIER_LABELS_TR,
    FeatureCard,
    FeatureDomain,
    FeatureStatus,
    FeatureTier,
)
from app.models.feature_card_event import (
    FEATURE_EVENT_TYPE_LABELS_TR,
    FeatureCardEvent,
    FeatureEventType,
)
from app.models.feature_bandit_state import FeatureBanditState
from app.models.feature_experiment import (
    EXPERIMENT_STATUS_BADGES,
    EXPERIMENT_STATUS_LABELS_TR,
    ExperimentStatus,
    FeatureExperiment,
)
from app.models.feature_flag import FeatureFlag, FeatureFlagOverride
from app.models.institution import Institution
from app.models.invoice import (
    INVOICE_OWNER_TYPES,
    INVOICE_STATUS_BADGE_COLOR,
    INVOICE_STATUS_LABELS_TR,
    Invoice,
    InvoiceStatus,
    PAYMENT_METHOD_LABELS_TR,
    PaymentMethod,
)
from app.models.invitation import (
    INVITATION_TTL_DAYS,
    Invitation,
    InvitationStatus,
    default_expiry as invitation_default_expiry,
)
from app.models.password_reset import (
    PASSWORD_RESET_TTL_MINUTES,
    PasswordResetToken,
    default_reset_expiry,
)
from app.models.email_verification import (
    EMAIL_VERIFICATION_TTL_DAYS,
    EmailVerificationToken,
    default_verification_expiry,
)
from app.models.totp_backup import TotpBackupCode
from app.models.offer import (
    OFFER_KIND_ICONS,
    OFFER_KIND_LABELS_TR,
    OFFER_OWNER_TYPES,
    OFFER_STATUS_COLORS,
    OFFER_STATUS_LABELS_TR,
    Offer,
    OfferKind,
    OfferStatus,
)
from app.models.campaign import (
    CAMPAIGN_RECIPIENT_OWNER_TYPES,
    CAMPAIGN_SEGMENT_DESCRIPTIONS,
    CAMPAIGN_SEGMENT_LABELS_TR,
    CAMPAIGN_STATUS_COLORS,
    CAMPAIGN_STATUS_LABELS_TR,
    Campaign,
    CampaignRecipient,
    CampaignSegment,
    CampaignStatus,
    RECIPIENT_STATUS_LABELS_TR,
    RecipientStatus,
)
from app.models.health_score_snapshot import (
    HEALTH_BAND_COLORS,
    HEALTH_BAND_EMOJIS,
    HEALTH_BAND_LABELS_TR,
    HEALTH_OWNER_TYPES,
    HealthScoreSnapshot,
    band_for_score,
)
from app.models.crm import (
    CRM_ACTION_KIND_ICONS,
    CRM_ACTION_KIND_LABELS_TR,
    CRM_ACTION_RESULT_COLORS,
    CRM_ACTION_RESULT_LABELS_TR,
    CRM_OWNER_TYPES,
    CrmAction,
    CrmActionKind,
    CrmActionResult,
    CrmNote,
)
from app.models.crm_template import CrmActionTemplate
from app.models.curriculum import (
    CURRICULUM_MODEL_LABELS,
    EXAM_SECTION_LABELS,
    MAARIF_FIRST_GRADE9_YEAR,
    CurriculumModel,
    ExamSection,
    Subject,
    Topic,
    derive_curriculum_model,
    estimate_entry_year_grade9,
)
from app.models.coach_billing import (
    COACH_PAYMENT_METHOD_LABELS,
    CoachPayment,
    CoachPaymentMethod,
    CoachStudentRate,
)
from app.models.coaching_session import (
    COACHING_CHANNEL_LABELS,
    COACHING_STATUS_LABELS,
    CoachingChannel,
    CoachingInsight,
    CoachingSession,
    CoachingSessionStatus,
    SessionCaptureSource,
)
from app.models.app_setting import AppSetting
from app.models.contact_request import (
    CONTACT_SOURCE_LABELS_TR,
    CONTACT_STATUS_CLOSED,
    CONTACT_STATUS_CONTACTED,
    CONTACT_STATUS_LABELS_TR,
    CONTACT_STATUS_NEW,
    ContactRequest,
)
from app.models.exam_result import ExamResult, compute_net, section_penalty
from app.models.support_request import (
    SUPPORT_ATTACH_ALLOWED_TYPES,
    SUPPORT_ATTACH_MAX_BYTES,
    SUPPORT_ATTACH_MAX_PER_REQUEST,
    SUPPORT_AUDIENCE_INSTITUTION_ADMIN,
    SUPPORT_AUDIENCE_LABELS_TR,
    SUPPORT_AUDIENCE_SUPER_ADMIN,
    SUPPORT_AUDIENCE_TEACHER,
    SUPPORT_CATEGORY_LABELS_TR,
    SUPPORT_OPEN_STATUSES,
    SUPPORT_RECIPIENT_PENDING_STATUSES,
    SUPPORT_STATUS_ANSWERED,
    SUPPORT_STATUS_LABELS_TR,
    SUPPORT_STATUS_OPEN,
    SUPPORT_STATUS_RESOLVED,
    SUPPORT_STATUS_UNDER_REVIEW,
    SUPPORT_STATUS_WITHDRAWN,
    SUPPORT_TERMINAL_STATUSES,
    SupportAttachment,
    SupportRequest,
    SupportRequestMessage,
)
from app.models.system_secret import SystemSecret
from app.models.task_template import TaskTemplate, TaskTemplateItem
from app.models.warning_state import WarningState
from app.models.owner_contact import OwnerContact
from app.models.owner_tag import (
    OWNER_TAG_COLORS,
    OWNER_TAG_DESCRIPTIONS,
    OWNER_TAG_ICONS,
    OWNER_TAG_LABELS_TR,
    OwnerTag,
    OwnerTagKind,
)
from app.models.parent import (
    NOTIFICATION_KIND_LABELS,
    PARENT_RELATION_LABELS,
    NotificationChannel,
    NotificationKind,
    NotificationLog,
    NotificationStatus,
    ParentInvitation,
    ParentNotificationPref,
    ParentPhoneVerification,
    ParentRelation,
    ParentSessionLog,
    ParentStudentLink,
    TeacherNoteToParent,
)
from app.models.payment_link import (
    LINK_OWNER_INSTITUTION,
    LINK_OWNER_USER,
    LINK_STATUS_ACTIVE,
    LINK_STATUS_CANCELLED,
    LINK_STATUS_CONSUMED,
    LINK_STATUS_EXPIRED,
    LINK_STATUS_LABELS_TR,
    PaymentLink,
)
from app.models.payment_transaction import (
    CYCLE_ANNUAL,
    CYCLE_MONTHLY,
    CYCLE_ONE_TIME,
    PROVIDER_IYZICO,
    PROVIDER_MANUAL,
    PROVIDER_SHOPIER,
    STATUS_3DS_PENDING,
    STATUS_EXPIRED,
    STATUS_FAILED,
    STATUS_LABELS_TR,
    STATUS_PENDING,
    STATUS_REFUNDED,
    STATUS_SUCCEEDED,
    PaymentTransaction,
)
from app.models.plan_history import (
    PlanChangeHistory,
    PlanChangeReason,
    PlanOwnerType,
)
from app.models.focus import (
    POMODORO_KIND_LABELS_TR,
    PomodoroKind,
    PomodoroSession,
    StudentBadge,
)
from app.models.progress import SectionProgress, StudentBook
from app.models.quota import InstitutionQuotaOverride
from app.models.review import (
    STATE_LABELS_TR as REVIEW_STATE_LABELS_TR,
    STATE_LEARNING as REVIEW_STATE_LEARNING,
    STATE_NEW as REVIEW_STATE_NEW,
    STATE_RELEARNING as REVIEW_STATE_RELEARNING,
    STATE_REVIEW as REVIEW_STATE_REVIEW,
    ReviewCard,
    ReviewLog,
)
from app.models.student_goal import (
    GOAL_KIND_EMOJIS,
    GOAL_KIND_LABELS_TR,
    GOAL_STATUS_LABELS_TR,
    GoalKind,
    GoalStatus,
    StudentGoal,
)
from app.models.suggestion_feedback import FeedbackAction, SuggestionFeedback
from app.models.task import Task, TaskBookItem, TaskStatus, TaskType
from app.models.week_note import WeekNote
from app.models.task_request import (
    REQUEST_STATUS_LABELS,
    REQUEST_TYPE_LABELS,
    RequestStatus,
    RequestType,
    TaskRequest,
)
from app.models.usage import (
    USAGE_KIND_LABELS_TR,
    CreditAccount,
    UsageEvent,
    UsageKind,
    UsageOwnerType,
)
from app.models.user import (
    GRADUATE_MODE_LABELS,
    TRACK_LABELS,
    GraduateMode,
    Track,
    User,
    UserRole,
)

__all__ = [
    "ACADEMIC_PHASE_KIND_BADGES",
    "ACADEMIC_PHASE_KIND_LABELS",
    "AT_RISK_MUTE_DAYS",
    "AUDIT_ACTION_LABELS",
    "AcademicPhase",
    "AcademicPhaseKind",
    "AcademicYear",
    "ABUSE_DEDUP_WINDOW_HOURS",
    "ALARM_DEFAULT_RULES",
    "AlarmEvent",
    "AlarmRule",
    "ERROR_RETENTION_DAYS",
    "ErrorEvent",
    "SLOW_REQUEST_THRESHOLD_MS",
    "SLOW_RETENTION_DAYS",
    "SlowRequestLog",
    "ABUSE_KIND_DESCRIPTIONS_TR",
    "ABUSE_KIND_LABELS_TR",
    "ABUSE_SEVERITY_BADGE_COLOR",
    "ABUSE_SEVERITY_LABELS_TR",
    "AbuseSignal",
    "ActiveSession",
    "AdminWeeklyDigest",
    "AtRiskMute",
    "AuditAction",
    "AuditLog",
    "BLOCK_REASON_LABELS_TR",
    "at_risk_mute_default_expiry",
    "Book",
    "BookSection",
    "BookSet",
    "BookSetItem",
    "BookTemplate",
    "BookTemplateSection",
    "BookType",
    "CRM_ACTION_KIND_ICONS",
    "CRM_ACTION_KIND_LABELS_TR",
    "CRM_ACTION_RESULT_COLORS",
    "CRM_ACTION_RESULT_LABELS_TR",
    "CRM_OWNER_TYPES",
    "CrmAction",
    "CrmActionKind",
    "CrmActionResult",
    "CrmActionTemplate",
    "CrmNote",
    "CronSchedule",
    "DATA_REQUEST_KIND_LABELS_TR",
    "DATA_REQUEST_STATUS_LABELS_TR",
    "DELETE_GRACE_PERIOD_DAYS",
    "DataRequestKind",
    "DataRequestStatus",
    "DataSubjectRequest",
    "CURRICULUM_MODEL_LABELS",
    "CurriculumModel",
    "COACHING_CHANNEL_LABELS",
    "COACHING_STATUS_LABELS",
    "CoachingChannel",
    "CoachingInsight",
    "CoachingSession",
    "CoachingSessionStatus",
    "AppSetting",
    "ContactRequest",
    "SupportRequest",
    "SupportRequestMessage",
    "SupportAttachment",
    "SUPPORT_ATTACH_ALLOWED_TYPES",
    "SUPPORT_ATTACH_MAX_BYTES",
    "SUPPORT_ATTACH_MAX_PER_REQUEST",
    "WarningState",
    "TaskTemplate",
    "TaskTemplateItem",
    "SUPPORT_AUDIENCE_SUPER_ADMIN",
    "SUPPORT_AUDIENCE_INSTITUTION_ADMIN",
    "SUPPORT_AUDIENCE_TEACHER",
    "SUPPORT_AUDIENCE_LABELS_TR",
    "SUPPORT_CATEGORY_LABELS_TR",
    "SUPPORT_STATUS_OPEN",
    "SUPPORT_STATUS_UNDER_REVIEW",
    "SUPPORT_STATUS_ANSWERED",
    "SUPPORT_STATUS_RESOLVED",
    "SUPPORT_STATUS_WITHDRAWN",
    "SUPPORT_STATUS_LABELS_TR",
    "SUPPORT_OPEN_STATUSES",
    "SUPPORT_TERMINAL_STATUSES",
    "SUPPORT_RECIPIENT_PENDING_STATUSES",
    "CONTACT_STATUS_NEW",
    "CONTACT_STATUS_CONTACTED",
    "CONTACT_STATUS_CLOSED",
    "CONTACT_STATUS_LABELS_TR",
    "CONTACT_SOURCE_LABELS_TR",
    "SystemSecret",
    "SessionCaptureSource",
    "COACH_PAYMENT_METHOD_LABELS",
    "CoachPayment",
    "CoachPaymentMethod",
    "CoachStudentRate",
    "EXAM_SECTION_LABELS",
    "EXAM_TARGET_LABELS",
    "ExamResult",
    "ExamSection",
    "ExamTarget",
    "compute_net",
    "section_penalty",
    "FeedbackAction",
    "MAARIF_FIRST_GRADE9_YEAR",
    "derive_curriculum_model",
    "estimate_entry_year_grade9",
    "GRADUATE_MODE_LABELS",
    "GraduateMode",
    "IMPERSONATION_END_REASON_LABELS_TR",
    "IMPERSONATION_MAX_DURATION_MINUTES",
    "IMPERSONATION_REASON_MAX_LENGTH",
    "IMPERSONATION_REASON_MIN_LENGTH",
    "ImpersonationSession",
    "INVITATION_TTL_DAYS",
    "INVOICE_OWNER_TYPES",
    "INVOICE_STATUS_BADGE_COLOR",
    "INVOICE_STATUS_LABELS_TR",
    "Institution",
    "Invitation",
    "InvitationStatus",
    "PASSWORD_RESET_TTL_MINUTES",
    "PasswordResetToken",
    "default_reset_expiry",
    "EMAIL_VERIFICATION_TTL_DAYS",
    "EmailVerificationToken",
    "default_verification_expiry",
    "TotpBackupCode",
    "Invoice",
    "InvoiceStatus",
    "invitation_default_expiry",
    "OwnerContact",
    "OWNER_TAG_COLORS",
    "OWNER_TAG_DESCRIPTIONS",
    "OWNER_TAG_ICONS",
    "OWNER_TAG_LABELS_TR",
    "OwnerTag",
    "OwnerTagKind",
    "OFFER_OWNER_TYPES",
    "OFFER_KIND_ICONS",
    "OFFER_KIND_LABELS_TR",
    "OFFER_STATUS_COLORS",
    "OFFER_STATUS_LABELS_TR",
    "Offer",
    "OfferKind",
    "OfferStatus",
    "CAMPAIGN_RECIPIENT_OWNER_TYPES",
    "CAMPAIGN_SEGMENT_DESCRIPTIONS",
    "CAMPAIGN_SEGMENT_LABELS_TR",
    "CAMPAIGN_STATUS_COLORS",
    "CAMPAIGN_STATUS_LABELS_TR",
    "Campaign",
    "CampaignRecipient",
    "CampaignSegment",
    "CampaignStatus",
    "RECIPIENT_STATUS_LABELS_TR",
    "RecipientStatus",
    "HEALTH_OWNER_TYPES",
    "HEALTH_BAND_COLORS",
    "HEALTH_BAND_EMOJIS",
    "HEALTH_BAND_LABELS_TR",
    "HealthScoreSnapshot",
    "band_for_score",
    "PAYMENT_METHOD_LABELS_TR",
    "PaymentMethod",
    "NOTIFICATION_KIND_LABELS",
    "NotificationChannel",
    "NotificationKind",
    "NotificationLog",
    "NotificationStatus",
    "PARENT_RELATION_LABELS",
    "ParentInvitation",
    "ParentNotificationPref",
    "ParentPhoneVerification",
    "ParentRelation",
    "ParentSessionLog",
    "ParentStudentLink",
    "REQUEST_STATUS_LABELS",
    "REQUEST_TYPE_LABELS",
    "RequestStatus",
    "RequestType",
    "SectionProgress",
    "GOAL_KIND_EMOJIS",
    "GOAL_KIND_LABELS_TR",
    "GOAL_STATUS_LABELS_TR",
    "GoalKind",
    "GoalStatus",
    "StudentGoal",
    "StudentBook",
    "Subject",
    "SuggestionFeedback",
    "SuspiciousIp",
    "THRESHOLD_MASS_INVITATION_PER_HOUR",
    "THRESHOLD_MASS_NOTIFICATION_PER_HOUR",
    "THRESHOLD_MULTI_ACCOUNT_DISTINCT_USERS",
    "THRESHOLD_UNSUBSCRIBE_SPIKE_PER_DAY",
    "TERMINATION_REASON_LABELS_TR",
    "TRACK_LABELS",
    "Task",
    "TaskBookItem",
    "TaskRequest",
    "TaskStatus",
    "TaskType",
    "TeacherNoteToParent",
    "Topic",
    "Track",
    "ADDON_DESCRIPTIONS_TR",
    "ADDON_LABELS_TR",
    "ADDON_MONTHLY_PRICE_TRY",
    "ADDON_MONTHLY_QUOTA",
    "Addon",
    "AddonKind",
    "AUDIENCE_LABELS_TR",
    "AnnouncementAudience",
    "AnnouncementSeverity",
    "FEATURE_DOMAIN_LABELS_TR",
    "FEATURE_EVENT_TYPE_LABELS_TR",
    "FEATURE_STATUS_BADGES",
    "FEATURE_STATUS_LABELS_TR",
    "FEATURE_TIER_LABELS_TR",
    "EXPERIMENT_STATUS_BADGES",
    "EXPERIMENT_STATUS_LABELS_TR",
    "ExperimentStatus",
    "FeatureBanditState",
    "FeatureCard",
    "FeatureCardEvent",
    "FeatureDomain",
    "FeatureEventType",
    "FeatureExperiment",
    "FeatureFlag",
    "FeatureFlagOverride",
    "FeatureStatus",
    "FeatureTier",
    "InstitutionQuotaOverride",
    "PlanChangeHistory",
    "PlanChangeReason",
    "PlanOwnerType",
    "POMODORO_KIND_LABELS_TR",
    "PomodoroKind",
    "PomodoroSession",
    "StudentBadge",
    "REVIEW_STATE_LABELS_TR",
    "REVIEW_STATE_LEARNING",
    "REVIEW_STATE_NEW",
    "REVIEW_STATE_RELEARNING",
    "REVIEW_STATE_REVIEW",
    "ReviewCard",
    "ReviewLog",
    "SEVERITY_LABELS_TR",
    "SystemAnnouncement",
    "USAGE_KIND_LABELS_TR",
    "CreditAccount",
    "UsageEvent",
    "UsageKind",
    "UsageOwnerType",
    "User",
    "UserRole",
    # Ödeme (Paket Ö1 + Ö2a)
    "PaymentTransaction",
    "PaymentLink",
    "LINK_STATUS_ACTIVE",
    "LINK_STATUS_CONSUMED",
    "LINK_STATUS_EXPIRED",
    "LINK_STATUS_CANCELLED",
    "LINK_STATUS_LABELS_TR",
    "LINK_OWNER_INSTITUTION",
    "LINK_OWNER_USER",
    "PROVIDER_IYZICO",
    "PROVIDER_SHOPIER",
    "PROVIDER_MANUAL",
    "STATUS_PENDING",
    "STATUS_3DS_PENDING",
    "STATUS_SUCCEEDED",
    "STATUS_FAILED",
    "STATUS_EXPIRED",
    "STATUS_REFUNDED",
    "STATUS_LABELS_TR",
    "CYCLE_MONTHLY",
    "CYCLE_ANNUAL",
    "CYCLE_ONE_TIME",
]
